const cards = [
     {
       name: "Ace",
       suit: "hearts",
       value: 11,
       id: "AceHearts",
     },
     {
       name: "Two",
       suit: "Hearts",
       value: 2,
       id: "2Hearts",
     },
     {
       name: "Three",
       suit: "Hearts",
       value: 3,
       id: "3Hearts",
     },
     {
       name: "Four",
       suit: "Hearts",
       value: 4,
       id: "4Hearts",
     },
     {
       name: "Five",
       suit: "Hearts",
       value: 5,
       id: "5Hearts",
     },
     {
       name: "Six",
       suit: "Hears",
       value: 6,
       id: "6Hearts",
     },
     {
       name: "Seven",
       suit: "Hearts",
       value: 7,
       id: "7Hearts",
     },
     {
       name: "Eight",
       suit: "Hearts",
       value: 8,
       id: "8Hearts",
     },
     {
       name: "Nine",
       suit: "Hearts",
       value: 9,
       id: "9Hearts",
     },
     {
       name: "Ten",
       suit: "Hearts",
       value: 10,
       id: "10Hearts",
     },
     {
       name: "Jack",
       suit: "Hearts",
       value: 10,
       id: "JackHearts",
     },
     {
       name: "Queen",
       suit: "Hearts",
       value: 10,
       id: "QueenHearts",
     },
     {
       name: "King",
       suit: "Hearts",
       value: 10,
       id: "KingHearts",
     },
    {
        name: "Ace",
        suit: "Diamonds",
        value: 11,
        id: "AceDiamonds",
    },
    {
        name: "Two",
        suit: "Diamonds",
        value: 2,
        id: "2Diamonds",
    },
    {
        name: "Three",
        suit: "Diamonds",
        value: 3,
        id: "3Diamonds",
    },
    {
        name: "Four",
        suit: "Diamonds",
        value: 4,
        id: "4Diamonds",
    },
    {
        name: "Five",
        suit: "Diamonds",
        value: 5,
        id: "5Diamonds",
    },
    {
        name: "Six",
        suit: "Diamonds",
        value: 6,
        id: "6Diamonds",
    },
    {
        name: "Seven",
        suit: "Diamonds",
        value: 7,
        id: "7Diamonds",
    },
    {
        name: "Eight",
        suit: "Diamonds",
        value: 8,
        id: "8Diamonds",
    },
    {
        name: "Nine",
        suit: "Diamonds",
        value: 9,
        id: "9Diamonds",
    },
    {
        name: "Ten",
        suit: "Diamonds",
        value: 10,
        id: "10Diamonds",
    },
    {
        name: "Jack",
        suit: "Diamonds",
        value: 10,
        id: "JackDiamonds",
    },
    {
        name: "Queen",
        suit: "Diamonds",
        value: 10,
        id: "QueenDiamonds",
    },
    {
        name: "King",
        suit: "Diamonds",
        value: 10,
        id: "KingDiamonds",
    },
    {
        name: "Ace",
        suit: "Spades",
        value: 11,
        id: "AceSpades",
    },
    {
        name: "Two",
        suit: "Spades",
        value: 2,
        id: "2Spades",
    },
    {
        name: "Three",
        suit: "Spades",
        value: 3,
        id: "3Spades",
    },
    {
        name: "Four",
        suit: "Spades",
        value: 4,
        id: "4Spades",
    },
    {
        name: "Five",
        suit: "Spades",
        value: 5,
        id: "5Spades",
    },
    {
        name: "Six",
        suit: "Spades",
        value: 6,
        id: "6Spades",
    },
    {
        name: "Seven",
        suit: "Spades",
        value: 7,
        id: "7Spades",
    },
    {
        name: "Eight",
        suit: "Spades",
        value: 8,
        id: "8Spades",
    },
    {
        name: "Nine",
        suit: "Spades",
        value: 9,
        id: "9Spades",
    },
    {
        name: "Ten",
        suit: "Spades",
        value: 10,
        id: "10Spades",
    },
    {
        name: "Jack",
        suit: "Spades",
        value: 10,
        id: "JackSpades",
    },
    {
        name: "Queen",
        suit: "Spades",
        value: 10,
        id: "QueenSpades",
    },
    {
        name: "King",
        suit: "Spades",
        value: 10,
        id: "KingSpades",
    },
    {
        name: "Ace",
        suit: "Clubs",
        value: 11,
        id: "AceClubs",   
    },
    {
        name: "Two",
        suit: "Clubs",
        value: 2,
        id: "2Clubs",
    },
    {
        name: "Three",
        suit: "Clubs",
        value: 3,
        id: "3Clubs",
    },
    {
        name: "Four",
        suit: "Clubs",
        value: 4,
        id: "4Clubs",
    },
    {
        name: "Five",
        suit: "Clubs",
        value: 5,
        id: "5Clubs",
    },
    {
        name: "Six",
        suit: "Clubs",
        value: 6,
        id: "6Clubs",
    },
    {
        name: "Seven",
        suit: "Clubs",
        value: 7,
        id: "7Clubs",
    },
    {
        name: "Eight",
        suit: "Clubs",
        value: 8,
        id: "8Clubs",
    },
    {
        name: "Nine",
        suit: "Clubs",
        value: 9,
        id: "9Clubs",
    },
    {
        name: "Ten",
        suit: "Clubs",
        value: 10,
        id: "10Clubs",
    },
    {
        name: "Jack",
        suit: "Clubs",
        value: 10,
        id: "JackClubs",
    },
    {
        name: "Queen",
        suit: "Clubs",
        value: 10,
        id: "QueenClubs",
    },
    {
        name: "King",
        suit: "Clubs",
        value: 10,
        id: "KingClubs",
    }
];

export default cards;

